### ISSUE TITLE
Attach to all forms or specific?

### ISSUE THREAD

**Issue by fleeting** [defvayne23/ValidInput#8]
Should it still query all forms or should we look for a data attribute on a form? Is there a downside to looking at all forms?

/cc @defvayne23

**Comment by fleeting** [comment]
I guess this goes with #1 actually.

**Comment by defvayne23** [comment]
I like the idea of not having to remember if it's attached to the form. It just works.

**Comment by defvayne23** [comment]
This does bring up that it needs to handle forms added to the DOM after initial load. Maybe we could move the submit event to the body instead of on the form. So submit would happen on ignored forms, but not move forward.
